config/routes.rb
Rails.application.routes.draw do
  
 
  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about', as: 'about'
  resources :users, only: [:index, :show, :edit, :update] 
  resources :books, only: [:new, :index, :show, :edit, :update, :create, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates  :user_id, uniqueness: {scope: :book_id}
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
         
  has_one_attached :profile_image
  
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  def get_profile_image(width, height)
    
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
    

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    comment = BookComment.new(book_comment_params)
    comment.user_id = current_user.id
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end
  
  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
     if @book.save
       flash[:notice]="You have created book successfully."
       redirect_to book_path(@book)
     else
       @books = Book.all
       @user = current_user
       render :index
       
     end
  end
  
  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @booknew = Book.new
    @book_comment = BookComment.new
  end
  
  def edit
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="You have updated book successfully."
      redirect_to book_path(@book)
    else 
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  
  private
  def book_params
    
    params.require(:book).permit(:title, :body)
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer 
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer 
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    comment = PostComment.new(post_comment_params)
    comment.user_id = current_user.id
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end
  
  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end
  
  private
  
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end
  
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h1>User info</h1>
<%= image_tag user.get_profile_image(100,100) %>
<p>name  　　　<%= user.name %></p>
<p>introduction 　　　<%= user.introduction %></p>
<%= link_to edit_user_path(user) do %>
 <i class="fas fa-user-cog"></i>
<% end %>


<!-/bookers2/app/views/books/new.html.erb--->

<h1>New book</h1>
<%= form_with model: book do |f| %>
  <label for="inputTitle">Title</label></br>
  <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"タイトル"%></br>
  <label for="inputBody">Opinion</label></br>
  <%= f.text_field :body, placeholder: "感想", id:"inputBody" %></br>  
  <%= f.submit "Create Book" %>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
 <% if @book.errors.count == 1 %>
   <%= @book.errors.count %>error :
  <% else %>
   <%= @book.errors.count %>errors :
 <% end %>
 <ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
 </ul>
<% end %>


<div class="container">
  <h1>Editing Book</h1>
  <div class="row justify-content-center">
    
    <div class="col-md-6">
      <%= form_with model: @book,local: true, class: "form-group" do |f| %>
        <div class="form-group">
          <label for="inputTitle">Title</label>
          <%= f.text_field :title, class: "form-control", id: "inputTitle", style: "width: 100%;" %>
        </div>

        <div class="form-group">
          <label for="inputOpinion">Opinion</label>
          <%= f.text_field :body, class: "form-control", id: "inputOpinion", style: "width: 100%;" %>
        </div>

        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-primary" %>
        </div>

        <div class="form-group">
          <%= link_to "Show", book_path(@book), class: "btn btn-secondary" %> 
          <%= link_to "Back", books_path, class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
 <% if @book.errors.count == 1 %>
   <%= @book.errors.count %>error :
  <% else %>
   <%= @book.errors.count %>errors :
 <% end %>
 <ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
 </ul>
<% end %>


<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'list', user: @user, book: @book %>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Image</th>
            <th scope="col">Title</th>
            <th scope="col">Body</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                  <%= link_to user_path(book.user) do %>
                     <%= image_tag(book.user.get_profile_image(100, 100)) %>
                  <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %>
               
              </td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorite_path(book), method: :delete do %>
                      <i class="fa-solid fa-heart"></i><%= book.favorites.count %> いいね
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorite_path(book), method: :post do %>
                      <i class="fa-regular fa-heart"></i><%= book.favorites.count %> いいね
                    <% end %>
                  </p>
                <% end %>     
                
              </td>
              <td><p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></p></td>
            </tr>
           
          <% end %>  
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3">
      <%= render 'list', user: @user, book: @booknew %>
    </div>
    

    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      
      <table class="table">
     
        <tbody>
          <tr>
            <td>
              <%= image_tag @book.user.get_profile_image(100, 100) %><br>
              <%= link_to @book.user.name, user_path(@book.user_id) %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book) %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <% if @book.user_id == current_user.id %>
              <td>
                <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-primary" %>
              </td>
              <td>
                 <%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
        <% if @book.favorited_by?(current_user) %>
          <p>
            <%= link_to book_favorite_path(@book), method: :delete do %>
              <i class="fa-solid fa-heart"></i><%= @book.favorites.count %> いいね
            <% end %>
          </p>
          <% else %>
          <p>
            <%= link_to book_favorite_path(@book), method: :post do %>
              <i class="fa-regular fa-heart"></i><%= @book.favorites.count %> いいね
            <% end %>
          </p>
        <% end %>      
     <div>
      <p>コメント件数：<%= @book.book_comments.count %></p>
      <% @book.book_comments.each do |book_comment| %>
        <p><%= image_tag book_comment.user.get_profile_image(100,100) %></p>
        <%= book_comment.user.name %>
        <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
        <% if book_comment.user == current_user %>
         <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-primary btn-sm" %>
        <% end %>
      <% end %>
    </div>
    <div>
      <%= form_with model: [@book, @book_comment] do |f| %>
        <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
        <%= f.submit "送信する" %>
      <% end %>
    </div>     
      
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to <i class="fa-solid fa-book"></i>Bookers!</h1>

app/views/homes/top.html.erb
 <div class="container">
  <div class="text-center">
       <h1>Welcomt to <i class="fa-solid fa-book"></i>Bookers!!</h1>
        
        <p>in Bookers,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div>
          <%= link_to "Log in", new_user_session_path,class: "btn btn-primary btn-sm" %>
        </div></br>
        <div>
          <%= link_to "Sign up", new_user_registration_path,class: "btn btn-success btn-sm" %>
        </div>
  </div>    
</div>
 

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
    <%= value %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/a15c77aa6a.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      body, html {
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100%;
      }
      header {
        background-color: gray;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a href="/" style="color: white;"><span>Bookers</span></a>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                   <div class="col-4" >                
                      <li class="nav-item" >
                        <%= link_to user_path(current_user.id), style: "color: white;" do %>
                         <i class="fa-solid fa-house"></i>Home
                        <% end %>
                      </li>
                    </div>
                     <div class="col-4">    
                      <li class="nav-item">
                        <%= link_to  users_path, style: "color: white;" do %>
                         <i class="fa-solid fa-users"></i>Users
                        <% end %>
                      </li>
                    </div> 
                     <div class="col-4">    
                      <li class="nav-item">
                        <%= link_to  books_path, style: "color: white;" do%>
                         <i class="fa-solid fa-book-open"></i>Books
                        <% end %>
                      </li>
                    </div> 
                     <div class="col-4">    
                      <li class="nav-item">
                        <%= link_to  destroy_user_session_path, method: :delete, style: "color: white;" do %>
                        <i class="fa-solid fa-right-from-bracket"></i>Log out
                        <% end %>
                      </li>
                    </div> 
                    <% else %>
                     <div class="col-4">     
                      <li class="nav-item">
                        <%= link_to root_path , style: "color: white;" do %>
                        <i class="fa-solid fa-house"></i>Home
                        <% end %>
                      </li>
                    </div> 
                     <div class="col-4">     
                      <li class="nav-item">
                        <%= link_to  about_path , style: "color: white;" do%>
                        <i class="fa-solid fa-link"></i>About
                        <% end %>
                      </li>
                    </div> 
                     <div class="col-4">     
                      <li class="nav-item">
                        <%= link_to new_user_registration_path, style: "color: white;" do %>
                         <i class="fa-solid fa-user-plus"></i>Sign up
                        <% end %>
                      </li>
                    </div> 
                     <div class="col-4">    
                      <li class="nav-item">
                        <%= link_to new_user_session_path, style: "color: white;" do %>
                        <i class="fa-solid fa-right-to-bracket"></i>Log in
                        <% end %>
                      </li>
                    </div> 
          
                    <% end %>
                
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <footer>
      <br>
      <p class="text-center">CopyRight Infratop.inc</p>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
 <% if @user.errors.count == 1 %>
   <%= @user.errors.count %>error :
  <% else %>
   <%= @user.errors.count %>errors :
 <% end %>
 <ul>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
 </ul>
<% end %>


<div class="container">  
      <h2>User info</h2>
      
    <div class="row justify-content-center">
     <div class="col-md-6">
      <%= form_with model: @user do |f| %>
       <div class="form-group">
        <label for="inputName">Name</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
       </div>
       
       <div class="form-group">
        <label for="inputImage">Image</label>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
       </div>
       
       <div class="form-group">
        <label for="inputIntroduction">Introduction</label>
        <%= f.text_field :introduction, id:"inputIntroduction"%>
       </div>
       <div class="form-group">
        <%= f.submit "Update User" %>
        </div>
      <% end %>
     </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', user: @user , book: @book %>
    </div>


    <div class="col-md-8 offset-md-1">
      <h1> Books</h1>
      <table class="table">
        <thead>
         <tr>
            <th scope="col">image</th>
            <th scope="col">name</th>
            <th scope="col"></th>
         </tr>
        </thead>
        <tbody>
         <% @users.each do |user| %>
          <tr>
           <td class="main"><%= image_tag user.get_profile_image(100,100) %></td>
           <td class="main"><%= user.name  %></td>
           <td class="main"><%= link_to "Show" , user_path(user) %></td>
          </tr>
         <% end %>  
        </tbody>
      </table>
    </div>
    
  </div>
  
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', user: @user , book: @book %>
    </div>
    


    <div class="col-md-8 offset-md-1">
      <h1> Books</h1>
      <table class="table">
        <thead>
         <tr>
           <th scope="col"></th>
            <th scope="col">Title</th>
            <th scope="col">Body</th>
            <th scope="col"></th>
            <th scope="col"></th>
         </tr>
        </thead>
        <tbody>
         <% @books.each do |book| %>
          <tr>
           <td class="main">
             
             <%= link_to user_path(book.user) do %>
                    <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </td>
           <td class="main"><%= link_to book.title, book_path(book)  %></td>
           <td class="main"><%= book.body %></td>
           <td>
             <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorite_path(book), method: :delete do %>
                      <i class="fa-solid fa-heart"></i><%= book.favorites.count %> いいね
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorite_path(book), method: :post do %>
                      <i class="fa-regular fa-heart"></i><%= book.favorites.count %> いいね
                    <% end %>
                  </p>
               <% end %>     
           </td>
           <td><p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></p></td>
          </tr>
          
         <% end %>  
        </tbody>
      </table>
    </div>
    
  </div>
  
</div>